# Baseline di confronto 

In [5]:
import pandas as pd
import numpy as np
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import os

X_train = pd.read_csv("../data/splitted_category/X_train.csv")
X_test = pd.read_csv("../data/splitted_category/X_test.csv")
y_train = pd.read_csv("../data/splitted_category/y_train.csv").values.ravel()
y_test = pd.read_csv("../data/splitted_category/y_test.csv").values.ravel()

dummy = DummyClassifier(strategy='stratified', random_state=42)
dummy.fit(X_train, y_train)



y_pred = dummy.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
cm = confusion_matrix(y_test, y_pred)

print("TEST METRICS:")

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print("Confusion Matrix:")
print(cm)

y_pred_train = dummy.predict(X_train)

print("TRAIN METRICS:")
print("Accuracy:", accuracy_score(y_train, y_pred_train))
print("Precision:", precision_score(y_train, y_pred_train, average='weighted'))
print("Recall:", recall_score(y_train, y_pred_train, average='weighted'))
print("F1-Score:", f1_score(y_train, y_pred_train, average='weighted'))
print("Confusion Matrix:")
print(confusion_matrix(y_train, y_pred_train))

TEST METRICS:
Accuracy: 0.0644
Precision: 0.0633
Recall: 0.0644
F1-Score: 0.0637
Confusion Matrix:
[[ 0  0  4  0  4  1  2  0  0  0  2  0  0  3  0  0  6  0]
 [ 0  0  2  1  2  2  1  0  0  0  2  0  0  0  1  0  3  0]
 [ 0  1  4  5  7  8  2  0  6  0  8  2  1  2  1  0  9  0]
 [ 0  0  0  2  4  7  1  1  0  0  3  5  0  4  0  0  3  0]
 [ 5  1  9  2  9 10  4  0  3  0 10  1  7  6  3  2  7  1]
 [ 1  0  3  9  9  9 13  0  9  2 15  5  8 11  0  1 14  3]
 [ 1  1  1  3  9 12  7  0  5  1  6  3  1  6  0  0  7  1]
 [ 0  0  0  0  0  2  1  0  0  0  1  0  1  1  0  0  1  0]
 [ 0  0  2  2 11  5  5  2  2  0 10  4  0  9  1  2  5  0]
 [ 1  0  3  0  0  1  0  0  2  0  0  1  0  2  0  0  2  0]
 [ 2  1  7  4 10 15  9  2  8  2  6  2  5  6  2  0 10  6]
 [ 2  1  0  1  5  6  1  0  1  1  2  0  0  0  2  0  5  0]
 [ 2  0  4  0  0  2  2  1  2  1  1  2  0  3  0  0  2  0]
 [ 1  0  4  1  5  5  7  0  5  0 10  1  5  3  1  0  8  2]
 [ 0  2  1  0  0  3  2  0  1  0  0  0  0  2  0  0  4  1]
 [ 0  0  1  0  1  1  1  0  0  1  3  0  0  3  0

In [8]:
import os

os.makedirs("../results/classification_category/baseline", exist_ok=True)

with open("../results/classification_category/baseline/baseline_category.txt", "w") as f:
    f.write(f"Accuracy: {accuracy:.4f}\n")
    f.write(f"Precision: {precision:.4f}\n")
    f.write(f"Recall: {recall:.4f}\n")
    f.write(f"F1-Score: {f1:.4f}\n")
    f.write("Confusion Matrix:\n")
    f.write(str(cm))