# Baseline di confronto 

In [1]:
import pandas as pd
import numpy as np
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import os

X_train = pd.read_csv("../data/splitted_category/X_train.csv")
X_test = pd.read_csv("../data/splitted_category/X_test.csv")
y_train = pd.read_csv("../data/splitted_category/y_train.csv").values.ravel()
y_test = pd.read_csv("../data/splitted_category/y_test.csv").values.ravel()

dummy = DummyClassifier(strategy='stratified', random_state=42)
dummy.fit(X_train, y_train)



y_pred = dummy.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
cm = confusion_matrix(y_test, y_pred)

print("TEST METRICS:")

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print("Confusion Matrix:")
print(cm)

y_pred_train = dummy.predict(X_train)

print("TRAIN METRICS:")
print("Accuracy:", accuracy_score(y_train, y_pred_train))
print("Precision:", precision_score(y_train, y_pred_train, average='weighted'))
print("Recall:", recall_score(y_train, y_pred_train, average='weighted'))
print("F1-Score:", f1_score(y_train, y_pred_train, average='weighted'))
print("Confusion Matrix:")
print(confusion_matrix(y_train, y_pred_train))

TEST METRICS:
Accuracy: 0.1894
Precision: 0.1875
Recall: 0.1894
F1-Score: 0.1881
Confusion Matrix:
[[ 7  3  3 17 16 14 11]
 [ 5  4  6 10 10 13  8]
 [ 3  0  0  8  5  8  6]
 [14  9  8 49 31 33 25]
 [14 11  5 48 37 25 24]
 [12 15  5 36 31 33 35]
 [18 12  2 24 29 30 20]]
TRAIN METRICS:
Accuracy: 0.170995670995671
Precision: 0.16981136178764222
Recall: 0.170995670995671
F1-Score: 0.1703615896174178
Confusion Matrix:
[[14 10  4 36 35 34 33]
 [ 7  8  3 38 23 31 21]
 [10  5  2 16 13 13 11]
 [44 22 13 82 82 78 75]
 [33 31 15 83 81 73 66]
 [35 18 14 91 84 82 65]
 [33 21 10 61 67 75 47]]


In [2]:
import os

os.makedirs("../results/classification_category/baseline", exist_ok=True)

with open("../results/classification_category/baseline/baseline_category.txt", "w") as f:
    f.write(f"Accuracy: {accuracy:.4f}\n")
    f.write(f"Precision: {precision:.4f}\n")
    f.write(f"Recall: {recall:.4f}\n")
    f.write(f"F1-Score: {f1:.4f}\n")
    f.write("Confusion Matrix:\n")
    f.write(str(cm))